#!/usr/bin/env python3
"""
run_batch_semantic_validation.py

Batch semantic-validation orchestrator.

Pipeline for each syntactically valid candidate:

    candidate.rebeca
        -> RMC code generation
        -> compile generated C++ model checker
        -> execute model checker
        -> produce XML result
        -> execute benchmark-specific evaluator
        -> store detailed semantic result

The runner is benchmark-independent. Benchmark-specific logic belongs in
separate evaluator scripts.

A failure in one candidate does not stop the remaining batch.
"""

from __future__ import annotations

import argparse
import csv
import json
import logging
import os
import shlex
import shutil
import subprocess
import sys
import time
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

PROJECT_ROOT = Path(__file__).resolve().parent.parent

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(
        0,
        str(PROJECT_ROOT),
    )

from semantic_validation.core.evaluator_registry import (
    available_benchmarks,
    get_benchmark_config,
)

LOGGER = logging.getLogger("semantic-batch-runner")


STATUS_SYNTAX_FAIL = "SYNTAX_FAIL"
STATUS_PENDING = "SEMANTIC_PENDING"
STATUS_RMC_GENERATION_ERROR = "RMC_GENERATION_ERROR"
STATUS_CPP_COMPILATION_ERROR = "CPP_COMPILATION_ERROR"
STATUS_MODEL_CHECKER_ERROR = "MODEL_CHECKER_ERROR"
STATUS_XML_NOT_FOUND = "XML_NOT_FOUND"
STATUS_EVALUATOR_ERROR = "EVALUATOR_ERROR"
STATUS_SEMANTIC_FAIL = "SEMANTIC_FAIL"
STATUS_FULL_PASS = "FULL_PASS"
STATUS_SKIPPED = "SKIPPED"


@dataclass
class CommandResult:
    command: list[str]
    command_text: str
    working_directory: str
    return_code: int | None
    elapsed_seconds: float
    timed_out: bool
    stdout_path: str
    stderr_path: str
    error: str | None


@dataclass
class BatchResult:
    candidate_id: str
    phase: str
    benchmark: str
    prompt_strategy: str
    setting: str
    model: str | None

    source_result_path: str
    candidate_code_path: str | None
    workspace_path: str | None

    syntax_pass: bool
    semantic_candidate: bool
    semantic_executed: bool
    semantic_pass: bool | None

    passed_tests: int | None
    failed_tests: int | None
    total_tests: int | None
    failed_test_ids: list[str]

    rmc_generation_success: bool
    cpp_compilation_success: bool
    model_checker_success: bool
    evaluator_success: bool

    trace_xml_path: str | None
    semantic_result_path: str | None

    overall_status: str
    error_stage: str | None
    error_message: str | None

    started_at: str
    finished_at: str
    elapsed_seconds: float


def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Run semantic validation for collected Rebeca candidates."
    )

    parser.add_argument(
        "--benchmark",
        choices=available_benchmarks(),
        default=None,
        help=(
            "Benchmark identifier used to select the semantic "
            "specification and evaluator automatically. "
            "Available benchmarks: "
            f"{', '.join(available_benchmarks())}"
        ),
    )

    parser.add_argument(
        "--manifest",
        type=Path,
        default=Path(
            "semantic_validation/batch_results/"
            "phase2_simple/simple_counter/reports/"
            "candidate_manifest.json"
        ),
        help="Candidate manifest generated by collect_semantic_candidates.py",
    )

    parser.add_argument(
        "--output-root",
        type=Path,
        default=Path(
            "semantic_validation/batch_results/" "phase2_simple/simple_counter"
        ),
        help="Root directory for semantic execution results.",
    )

    parser.add_argument(
        "--rmc-jar",
        type=Path,
        required=True,
        help="Path to the RMC jar file.",
    )

    parser.add_argument(
        "--java-bin",
        default="java",
        help="Java executable. Default: java",
    )

    parser.add_argument(
        "--gpp-bin",
        default="g++",
        help="C++ compiler executable. Default: g++",
    )

    parser.add_argument(
        "--rmc-extension",
        default="CORE_REBECA",
        help="RMC extension passed to -e. Default: CORE_REBECA",
    )

    parser.add_argument(
        "--rmc-extra-arg",
        action="append",
        default=[],
        help=(
            "Additional RMC argument. May be specified multiple times. "
            "Example: --rmc-extra-arg=--tracegenerator"
        ),
    )

    parser.add_argument(
        "--model-checker-arg",
        action="append",
        default=[],
        help=("Additional model-checker argument. May be specified multiple " "times."),
    )

    parser.add_argument(
        "--trace-file-name",
        default="result.xml",
        help="Expected trace XML filename. Default: result.xml",
    )

    parser.add_argument(
        "--spec",
        type=Path,
        default=None,
        help=(
            "Optional semantic specification override. "
            "When omitted, it is selected from --benchmark."
        ),
    )

    parser.add_argument(
        "--evaluator",
        type=Path,
        default=None,
        help=(
            "Optional evaluator override. "
            "When omitted, it is selected from --benchmark."
        ),
    )

    parser.add_argument(
        "--python-bin",
        default=sys.executable,
        help="Python executable used to run the evaluator.",
    )

    parser.add_argument(
        "--rmc-timeout",
        type=int,
        default=120,
        help="RMC generation timeout in seconds. Default: 120",
    )

    parser.add_argument(
        "--compile-timeout",
        type=int,
        default=120,
        help="C++ compilation timeout in seconds. Default: 120",
    )

    parser.add_argument(
        "--model-checker-timeout",
        type=int,
        default=300,
        help="Model-checker timeout in seconds. Default: 300",
    )

    parser.add_argument(
        "--evaluator-timeout",
        type=int,
        default=120,
        help="Evaluator timeout in seconds. Default: 120",
    )

    parser.add_argument(
        "--candidate-id",
        action="append",
        default=[],
        help=("Run only specific candidate IDs. May be supplied multiple times."),
    )

    parser.add_argument(
        "--prompt-strategy",
        action="append",
        default=[],
        help=(
            "Run only selected prompt strategies. " "May be supplied multiple times."
        ),
    )

    parser.add_argument(
        "--limit",
        type=int,
        default=None,
        help="Maximum number of semantic candidates to execute.",
    )

    parser.add_argument(
        "--resume",
        action="store_true",
        help="Skip candidates that already have a terminal result.",
    )

    parser.add_argument(
        "--rerun-failed",
        action="store_true",
        help="With --resume, rerun previous failures but skip FULL_PASS results.",
    )

    parser.add_argument(
        "--clean-workspace",
        action="store_true",
        help="Delete each candidate workspace before executing it.",
    )

    parser.add_argument(
        "--keep-generated-files",
        action="store_true",
        help="Keep generated C++ and model-checker files.",
    )

    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show selected candidates without running RMC.",
    )

    parser.add_argument(
        "--verbose",
        action="store_true",
        help="Enable detailed logging.",
    )

    return parser.parse_args()


def resolve_benchmark_components(
    args: argparse.Namespace,
) -> None:
    """
    Resolve semantic specification and evaluator paths.

    Priority:
      1. Explicit --spec or --evaluator override
      2. Paths registered for --benchmark
    """

    config = None

    if args.benchmark is not None:
        config = get_benchmark_config(args.benchmark)

    if args.spec is None:
        if config is None:
            raise ValueError("Either --benchmark or --spec must be provided.")

        args.spec = config.spec_path

    if args.evaluator is None:
        if config is None:
            raise ValueError("Either --benchmark or --evaluator must be provided.")

        args.evaluator = config.evaluator_path

    args.spec = args.spec.expanduser().resolve()
    args.evaluator = args.evaluator.expanduser().resolve()

    if not args.spec.is_file():
        raise FileNotFoundError(
            f"Semantic specification does not exist: " f"{args.spec}"
        )

    if not args.evaluator.is_file():
        raise FileNotFoundError(
            f"Semantic evaluator does not exist: " f"{args.evaluator}"
        )


def resolve_benchmark_components(
    args: argparse.Namespace,
) -> None:
    """
    Resolve semantic specification and evaluator paths.

    Priority:
      1. Explicit --spec or --evaluator override
      2. Paths registered for --benchmark
    """

    config = None

    if args.benchmark is not None:
        config = get_benchmark_config(args.benchmark)

    if args.spec is None:
        if config is None:
            raise ValueError("Either --benchmark or --spec must be provided.")

        args.spec = config.spec_path

    if args.evaluator is None:
        if config is None:
            raise ValueError("Either --benchmark or --evaluator must be provided.")

        args.evaluator = config.evaluator_path

    args.spec = args.spec.expanduser().resolve()
    args.evaluator = args.evaluator.expanduser().resolve()

    if not args.spec.is_file():
        raise FileNotFoundError(
            f"Semantic specification does not exist: " f"{args.spec}"
        )

    if not args.evaluator.is_file():
        raise FileNotFoundError(
            f"Semantic evaluator does not exist: " f"{args.evaluator}"
        )


def configure_logging(verbose: bool) -> None:
    logging.basicConfig(
        level=logging.DEBUG if verbose else logging.INFO,
        format="[%(levelname)s] %(message)s",
    )


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()


def load_json(path: Path) -> Any:
    with path.open("r", encoding="utf-8") as file:
        return json.load(file)


def write_json(path: Path, value: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)

    with path.open("w", encoding="utf-8") as file:
        json.dump(value, file, ensure_ascii=False, indent=2)
        file.write("\n")


def write_jsonl(path: Path, values: list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)

    with path.open("w", encoding="utf-8") as file:
        for value in values:
            file.write(json.dumps(value, ensure_ascii=False))
            file.write("\n")


def safe_name(value: str) -> str:
    allowed = set(
        "abcdefghijklmnopqrstuvwxyz" "ABCDEFGHIJKLMNOPQRSTUVWXYZ" "0123456789" "._-"
    )

    normalized = "".join(
        character if character in allowed else "_" for character in value
    )

    normalized = normalized.strip("._-")
    return normalized or "unknown"


def run_command(
    command: list[str],
    cwd: Path,
    stdout_path: Path,
    stderr_path: Path,
    timeout_seconds: int,
) -> CommandResult:
    stdout_path.parent.mkdir(parents=True, exist_ok=True)
    stderr_path.parent.mkdir(parents=True, exist_ok=True)

    started = time.monotonic()
    timed_out = False
    return_code: int | None = None
    error_message: str | None = None

    LOGGER.debug(
        "Running command in %s: %s",
        cwd,
        shlex.join(command),
    )

    try:
        with (
            stdout_path.open("w", encoding="utf-8") as stdout_file,
            stderr_path.open("w", encoding="utf-8") as stderr_file,
        ):
            completed = subprocess.run(
                command,
                cwd=cwd,
                stdout=stdout_file,
                stderr=stderr_file,
                text=True,
                timeout=timeout_seconds,
                check=False,
            )

            return_code = completed.returncode

    except subprocess.TimeoutExpired:
        timed_out = True
        error_message = f"Command exceeded timeout of {timeout_seconds} seconds."

    except OSError as error:
        error_message = str(error)

    elapsed = time.monotonic() - started

    return CommandResult(
        command=command,
        command_text=shlex.join(command),
        working_directory=str(cwd.resolve()),
        return_code=return_code,
        elapsed_seconds=round(elapsed, 6),
        timed_out=timed_out,
        stdout_path=str(stdout_path.resolve()),
        stderr_path=str(stderr_path.resolve()),
        error=error_message,
    )


def command_succeeded(result: CommandResult) -> bool:
    return not result.timed_out and result.error is None and result.return_code == 0


def find_generated_cpp_files(workspace: Path) -> list[Path]:
    excluded_names = {
        "model_checker",
    }

    return sorted(
        path for path in workspace.rglob("*.cpp") if path.name not in excluded_names
    )


def find_trace_xml(
    workspace: Path,
    expected_name: str,
) -> Path | None:
    direct_path = workspace / expected_name

    if direct_path.exists():
        return direct_path

    matches = sorted(workspace.rglob(expected_name))

    if matches:
        return matches[0]

    xml_files = sorted(workspace.rglob("*.xml"))

    if len(xml_files) == 1:
        return xml_files[0]

    return None


def load_previous_results(path: Path) -> dict[str, dict[str, Any]]:
    if not path.exists():
        return {}

    try:
        raw = load_json(path)
    except (OSError, json.JSONDecodeError):
        LOGGER.warning(
            "Could not read previous result file: %s",
            path,
        )
        return {}

    if not isinstance(raw, list):
        return {}

    return {
        str(record.get("candidate_id")): record
        for record in raw
        if isinstance(record, dict) and record.get("candidate_id")
    }


def is_terminal_status(status: str | None) -> bool:
    return status in {
        STATUS_RMC_GENERATION_ERROR,
        STATUS_CPP_COMPILATION_ERROR,
        STATUS_MODEL_CHECKER_ERROR,
        STATUS_XML_NOT_FOUND,
        STATUS_EVALUATOR_ERROR,
        STATUS_SEMANTIC_FAIL,
        STATUS_FULL_PASS,
    }


def should_skip_previous(
    previous: dict[str, Any] | None,
    resume: bool,
    rerun_failed: bool,
) -> bool:
    if not resume or previous is None:
        return False

    status = previous.get("overall_status")

    if not is_terminal_status(status):
        return False

    if rerun_failed:
        return status == STATUS_FULL_PASS

    return True


def filter_candidates(
    manifest: list[dict[str, Any]],
    candidate_ids: list[str],
    prompt_strategies: list[str],
    limit: int | None,
) -> list[dict[str, Any]]:
    selected = [
        record for record in manifest if record.get("semantic_candidate") is True
    ]

    if candidate_ids:
        requested_ids = set(candidate_ids)

        selected = [
            record for record in selected if record.get("candidate_id") in requested_ids
        ]

    if prompt_strategies:
        requested_prompts = set(prompt_strategies)

        selected = [
            record
            for record in selected
            if record.get("prompt_strategy") in requested_prompts
        ]

    selected.sort(
        key=lambda record: (
            str(record.get("prompt_strategy") or ""),
            str(record.get("setting") or ""),
            str(record.get("model") or ""),
            str(record.get("candidate_id") or ""),
        )
    )

    if limit is not None:
        selected = selected[:limit]

    return selected


def parse_evaluator_result(
    result_path: Path,
) -> tuple[
    bool,
    bool,
    int | None,
    int | None,
    int | None,
    list[str],
    str | None,
]:
    if not result_path.exists():
        return (
            False,
            False,
            None,
            None,
            None,
            [],
            "Evaluator completed without producing its result JSON.",
        )

    try:
        result = load_json(result_path)
    except (OSError, json.JSONDecodeError) as error:
        return (
            False,
            False,
            None,
            None,
            None,
            [],
            f"Could not parse evaluator result: {error}",
        )

    if not isinstance(result, dict):
        return (
            False,
            False,
            None,
            None,
            None,
            [],
            "Evaluator result must be a JSON object.",
        )

    semantic_pass = result.get("semantic_pass")

    if not isinstance(semantic_pass, bool):
        semantic_pass = result.get("passed")

    if not isinstance(semantic_pass, bool):
        return (
            False,
            False,
            None,
            None,
            None,
            [],
            "Evaluator result does not contain a boolean semantic_pass.",
        )

    passed_tests = result.get("passed_tests")
    failed_tests = result.get("failed_tests")
    total_tests = result.get("total_tests")
    failed_test_ids = result.get("failed_test_ids", [])

    if not isinstance(failed_test_ids, list):
        failed_test_ids = []

    failed_test_ids = [str(test_id) for test_id in failed_test_ids]

    return (
        True,
        semantic_pass,
        passed_tests if isinstance(passed_tests, int) else None,
        failed_tests if isinstance(failed_tests, int) else None,
        total_tests if isinstance(total_tests, int) else None,
        failed_test_ids,
        None,
    )


def make_base_result(
    candidate: dict[str, Any],
    started_at: str,
) -> BatchResult:
    return BatchResult(
        candidate_id=str(candidate.get("candidate_id")),
        phase=str(candidate.get("phase") or ""),
        benchmark=str(candidate.get("benchmark") or ""),
        prompt_strategy=str(candidate.get("prompt_strategy") or ""),
        setting=str(candidate.get("setting") or ""),
        model=candidate.get("model"),
        source_result_path=str(candidate.get("source_result_path") or ""),
        candidate_code_path=candidate.get("candidate_code_path"),
        workspace_path=None,
        syntax_pass=bool(candidate.get("syntax_pass")),
        semantic_candidate=bool(candidate.get("semantic_candidate")),
        semantic_executed=False,
        semantic_pass=None,
        passed_tests=None,
        failed_tests=None,
        total_tests=None,
        failed_test_ids=[],
        rmc_generation_success=False,
        cpp_compilation_success=False,
        model_checker_success=False,
        evaluator_success=False,
        trace_xml_path=None,
        semantic_result_path=None,
        overall_status=STATUS_PENDING,
        error_stage=None,
        error_message=None,
        started_at=started_at,
        finished_at="",
        elapsed_seconds=0.0,
    )


def finalize_failure(
    result: BatchResult,
    started_monotonic: float,
    status: str,
    error_stage: str,
    error_message: str,
) -> BatchResult:
    result.overall_status = status
    result.error_stage = error_stage
    result.error_message = error_message
    result.finished_at = utc_now()
    result.elapsed_seconds = round(
        time.monotonic() - started_monotonic,
        6,
    )

    return result


def run_candidate(
    candidate: dict[str, Any],
    args: argparse.Namespace,
    executions_root: Path,
) -> BatchResult:
    started_at = utc_now()
    started_monotonic = time.monotonic()

    result = make_base_result(candidate, started_at)

    candidate_id = result.candidate_id
    prompt_strategy = safe_name(result.prompt_strategy)
    setting = safe_name(result.setting)

    workspace = executions_root / prompt_strategy / setting / safe_name(candidate_id)

    result.workspace_path = str(workspace.resolve())

    if args.clean_workspace and workspace.exists():
        shutil.rmtree(workspace)

    workspace.mkdir(parents=True, exist_ok=True)

    logs_directory = workspace / "logs"
    artifacts_directory = workspace / "artifacts"

    logs_directory.mkdir(parents=True, exist_ok=True)
    artifacts_directory.mkdir(parents=True, exist_ok=True)

    candidate_source = Path(str(candidate.get("candidate_code_path") or ""))

    if not candidate_source.exists():
        return finalize_failure(
            result=result,
            started_monotonic=started_monotonic,
            status=STATUS_RMC_GENERATION_ERROR,
            error_stage="candidate_preparation",
            error_message=(f"Candidate file does not exist: {candidate_source}"),
        )

    workspace_candidate = workspace / "candidate.rebeca"
    shutil.copy2(candidate_source, workspace_candidate)

    execution_metadata = {
        "candidate": candidate,
        "runner": {
            "rmc_jar": str(args.rmc_jar.resolve()),
            "java_bin": args.java_bin,
            "gpp_bin": args.gpp_bin,
            "rmc_extension": args.rmc_extension,
            "rmc_extra_args": args.rmc_extra_arg,
            "model_checker_args": args.model_checker_arg,
            "spec": str(args.spec.resolve()),
            "evaluator": str(args.evaluator.resolve()),
        },
    }

    write_json(
        workspace / "execution_metadata.json",
        execution_metadata,
    )

    # ------------------------------------------------------------------
    # Stage 1: RMC code generation
    # ------------------------------------------------------------------

    rmc_command = [
        args.java_bin,
        "-jar",
        str(args.rmc_jar.resolve()),
        "-s",
        str(workspace_candidate.resolve()),
        "-e",
        args.rmc_extension,
        *args.rmc_extra_arg,
    ]

    rmc_result = run_command(
        command=rmc_command,
        cwd=workspace,
        stdout_path=logs_directory / "rmc_stdout.log",
        stderr_path=logs_directory / "rmc_stderr.log",
        timeout_seconds=args.rmc_timeout,
    )

    write_json(
        artifacts_directory / "rmc_command_result.json",
        asdict(rmc_result),
    )

    if not command_succeeded(rmc_result):
        message = (
            rmc_result.error or f"RMC returned exit code {rmc_result.return_code}."
        )

        return finalize_failure(
            result=result,
            started_monotonic=started_monotonic,
            status=STATUS_RMC_GENERATION_ERROR,
            error_stage="rmc_generation",
            error_message=message,
        )

    result.rmc_generation_success = True

    # ------------------------------------------------------------------
    # Stage 2: compile generated C++
    # ------------------------------------------------------------------

    cpp_files = find_generated_cpp_files(workspace)

    if not cpp_files:
        return finalize_failure(
            result=result,
            started_monotonic=started_monotonic,
            status=STATUS_CPP_COMPILATION_ERROR,
            error_stage="cpp_discovery",
            error_message=("RMC completed successfully but generated no C++ files."),
        )

    model_checker_path = workspace / "model_checker"

    compile_command = [
        args.gpp_bin,
        "-std=c++11",
        *[str(path.resolve()) for path in cpp_files],
        "-o",
        str(model_checker_path.resolve()),
    ]

    compile_result = run_command(
        command=compile_command,
        cwd=workspace,
        stdout_path=logs_directory / "compile_stdout.log",
        stderr_path=logs_directory / "compile_stderr.log",
        timeout_seconds=args.compile_timeout,
    )

    write_json(
        artifacts_directory / "compile_command_result.json",
        asdict(compile_result),
    )

    if not command_succeeded(compile_result):
        message = compile_result.error or (
            "C++ compiler returned exit code " f"{compile_result.return_code}."
        )

        return finalize_failure(
            result=result,
            started_monotonic=started_monotonic,
            status=STATUS_CPP_COMPILATION_ERROR,
            error_stage="cpp_compilation",
            error_message=message,
        )

    result.cpp_compilation_success = True

    # ------------------------------------------------------------------
    # Stage 3: execute generated model checker
    # ------------------------------------------------------------------

    expected_xml_path = workspace / args.trace_file_name

    model_checker_command = [
        str(model_checker_path.resolve()),
        "-o",
        str(expected_xml_path.resolve()),
        *args.model_checker_arg,
    ]

    model_checker_result = run_command(
        command=model_checker_command,
        cwd=workspace,
        stdout_path=logs_directory / "model_checker_stdout.log",
        stderr_path=logs_directory / "model_checker_stderr.log",
        timeout_seconds=args.model_checker_timeout,
    )

    write_json(
        artifacts_directory / "model_checker_command_result.json",
        asdict(model_checker_result),
    )

    if not command_succeeded(model_checker_result):
        message = model_checker_result.error or (
            "Model checker returned exit code " f"{model_checker_result.return_code}."
        )

        return finalize_failure(
            result=result,
            started_monotonic=started_monotonic,
            status=STATUS_MODEL_CHECKER_ERROR,
            error_stage="model_checker_execution",
            error_message=message,
        )

    result.model_checker_success = True

    trace_xml_path = find_trace_xml(
        workspace=workspace,
        expected_name=args.trace_file_name,
    )

    if trace_xml_path is None:
        return finalize_failure(
            result=result,
            started_monotonic=started_monotonic,
            status=STATUS_XML_NOT_FOUND,
            error_stage="trace_discovery",
            error_message=("Model checker completed but no trace XML was found."),
        )

    result.trace_xml_path = str(trace_xml_path.resolve())

    # ------------------------------------------------------------------
    # Stage 4: benchmark-specific evaluator
    # ------------------------------------------------------------------

    semantic_result_path = artifacts_directory / "semantic_result.json"

    evaluator_command = [
        args.python_bin,
        str(args.evaluator.resolve()),
        "--trace",
        str(trace_xml_path.resolve()),
        "--spec",
        str(args.spec.resolve()),
        "--candidate",
        str(workspace_candidate.resolve()),
        "--metadata",
        str((workspace / "execution_metadata.json").resolve()),
        "--output",
        str(semantic_result_path.resolve()),
    ]

    evaluator_result = run_command(
        command=evaluator_command,
        cwd=workspace,
        stdout_path=logs_directory / "evaluator_stdout.log",
        stderr_path=logs_directory / "evaluator_stderr.log",
        timeout_seconds=args.evaluator_timeout,
    )

    write_json(
        artifacts_directory / "evaluator_command_result.json",
        asdict(evaluator_result),
    )

    result.semantic_executed = True
    result.semantic_result_path = str(semantic_result_path.resolve())

    if not command_succeeded(evaluator_result):
        message = evaluator_result.error or (
            "Evaluator returned exit code " f"{evaluator_result.return_code}."
        )

        return finalize_failure(
            result=result,
            started_monotonic=started_monotonic,
            status=STATUS_EVALUATOR_ERROR,
            error_stage="semantic_evaluator",
            error_message=message,
        )

    (
        evaluator_output_valid,
        semantic_pass,
        passed_tests,
        failed_tests,
        total_tests,
        failed_test_ids,
        evaluator_parse_error,
    ) = parse_evaluator_result(semantic_result_path)

    if not evaluator_output_valid:
        return finalize_failure(
            result=result,
            started_monotonic=started_monotonic,
            status=STATUS_EVALUATOR_ERROR,
            error_stage="evaluator_result_parsing",
            error_message=(evaluator_parse_error or "Evaluator output is invalid."),
        )

    result.evaluator_success = True
    result.semantic_pass = semantic_pass
    result.passed_tests = passed_tests
    result.failed_tests = failed_tests
    result.total_tests = total_tests
    result.failed_test_ids = failed_test_ids

    result.overall_status = STATUS_FULL_PASS if semantic_pass else STATUS_SEMANTIC_FAIL

    result.finished_at = utc_now()
    result.elapsed_seconds = round(
        time.monotonic() - started_monotonic,
        6,
    )

    if not args.keep_generated_files:
        for cpp_file in cpp_files:
            try:
                cpp_file.unlink()
            except OSError:
                LOGGER.debug(
                    "Could not remove generated C++ file: %s",
                    cpp_file,
                )

        try:
            model_checker_path.unlink()
        except OSError:
            pass

    return result


def write_csv(
    path: Path,
    results: list[BatchResult],
) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)

    field_names = [
        "candidate_id",
        "phase",
        "benchmark",
        "prompt_strategy",
        "setting",
        "model",
        "syntax_pass",
        "semantic_candidate",
        "semantic_executed",
        "semantic_pass",
        "passed_tests",
        "failed_tests",
        "total_tests",
        "failed_test_ids",
        "rmc_generation_success",
        "cpp_compilation_success",
        "model_checker_success",
        "evaluator_success",
        "overall_status",
        "error_stage",
        "error_message",
        "elapsed_seconds",
        "source_result_path",
        "candidate_code_path",
        "workspace_path",
        "trace_xml_path",
        "semantic_result_path",
        "started_at",
        "finished_at",
    ]

    with path.open(
        "w",
        encoding="utf-8",
        newline="",
    ) as file:
        writer = csv.DictWriter(
            file,
            fieldnames=field_names,
        )

        writer.writeheader()

        for result in results:
            row = asdict(result)
            row["failed_test_ids"] = "|".join(result.failed_test_ids)

            writer.writerow(
                {field_name: row.get(field_name) for field_name in field_names}
            )


def build_summary(
    manifest: list[dict[str, Any]],
    batch_results: list[BatchResult],
) -> dict[str, Any]:
    syntax_passed = sum(record.get("syntax_pass") is True for record in manifest)

    syntax_failed = sum(record.get("syntax_pass") is not True for record in manifest)

    semantic_candidates = sum(
        record.get("semantic_candidate") is True for record in manifest
    )

    executed = sum(result.semantic_executed for result in batch_results)

    semantic_passed = sum(
        result.overall_status == STATUS_FULL_PASS for result in batch_results
    )

    semantic_failed = sum(
        result.overall_status == STATUS_SEMANTIC_FAIL for result in batch_results
    )

    infrastructure_errors = sum(
        result.overall_status
        in {
            STATUS_RMC_GENERATION_ERROR,
            STATUS_CPP_COMPILATION_ERROR,
            STATUS_MODEL_CHECKER_ERROR,
            STATUS_XML_NOT_FOUND,
            STATUS_EVALUATOR_ERROR,
        }
        for result in batch_results
    )

    by_status: dict[str, int] = {}

    for result in batch_results:
        by_status[result.overall_status] = by_status.get(result.overall_status, 0) + 1

    prompt_names = sorted(
        {
            str(record.get("prompt_strategy"))
            for record in manifest
            if record.get("prompt_strategy")
        }
    )

    by_prompt: list[dict[str, Any]] = []

    for prompt_name in prompt_names:
        prompt_manifest = [
            record
            for record in manifest
            if record.get("prompt_strategy") == prompt_name
        ]

        prompt_results = [
            result for result in batch_results if result.prompt_strategy == prompt_name
        ]

        total = len(prompt_manifest)
        prompt_syntax_passed = sum(
            record.get("syntax_pass") is True for record in prompt_manifest
        )

        prompt_semantic_passed = sum(
            result.overall_status == STATUS_FULL_PASS for result in prompt_results
        )

        prompt_semantic_failed = sum(
            result.overall_status == STATUS_SEMANTIC_FAIL for result in prompt_results
        )

        by_prompt.append(
            {
                "prompt_strategy": prompt_name,
                "total_experiments": total,
                "syntax_passed": prompt_syntax_passed,
                "syntax_failed": total - prompt_syntax_passed,
                "semantic_candidates": sum(
                    record.get("semantic_candidate") is True
                    for record in prompt_manifest
                ),
                "semantic_executed": sum(
                    result.semantic_executed for result in prompt_results
                ),
                "semantic_passed": prompt_semantic_passed,
                "semantic_failed": prompt_semantic_failed,
                "full_pass_rate_over_all_experiments": (
                    round(prompt_semantic_passed / total, 6) if total else 0.0
                ),
                "semantic_pass_rate_over_syntax_passed": (
                    round(
                        prompt_semantic_passed / prompt_syntax_passed,
                        6,
                    )
                    if prompt_syntax_passed
                    else 0.0
                ),
            }
        )

    return {
        "generated_at": utc_now(),
        "total_experiments": len(manifest),
        "syntax_passed": syntax_passed,
        "syntax_failed": syntax_failed,
        "semantic_candidates": semantic_candidates,
        "batch_results": len(batch_results),
        "semantic_executed": executed,
        "semantic_passed": semantic_passed,
        "semantic_failed": semantic_failed,
        "infrastructure_errors": infrastructure_errors,
        "full_pass_rate_over_all_experiments": (
            round(semantic_passed / len(manifest), 6) if manifest else 0.0
        ),
        "semantic_pass_rate_over_syntax_passed": (
            round(semantic_passed / syntax_passed, 6) if syntax_passed else 0.0
        ),
        "by_status": by_status,
        "by_prompt_strategy": by_prompt,
    }


def save_reports(
    reports_directory: Path,
    results_by_id: dict[str, BatchResult],
    manifest: list[dict[str, Any]],
) -> None:
    ordered_results = sorted(
        results_by_id.values(),
        key=lambda result: (
            result.prompt_strategy,
            result.setting,
            result.model or "",
            result.candidate_id,
        ),
    )

    serialized = [asdict(result) for result in ordered_results]

    write_json(
        reports_directory / "semantic_results.json",
        serialized,
    )

    write_jsonl(
        reports_directory / "semantic_results.jsonl",
        serialized,
    )

    write_csv(
        reports_directory / "semantic_results.csv",
        ordered_results,
    )

    write_json(
        reports_directory / "semantic_summary.json",
        build_summary(
            manifest=manifest,
            batch_results=ordered_results,
        ),
    )


def validate_paths(args: argparse.Namespace) -> bool:
    required_files = {
        "manifest": args.manifest,
        "RMC jar": args.rmc_jar,
        "semantic specification": args.spec,
        "evaluator": args.evaluator,
    }

    valid = True

    for label, path in required_files.items():
        resolved = path.expanduser().resolve()

        if not resolved.is_file():
            LOGGER.error("%s not found: %s", label, resolved)
            valid = False

    return valid


def main() -> int:
    args = parse_arguments()

    try:
        resolve_benchmark_components(args)
    except (
        ValueError,
        FileNotFoundError,
    ) as error:
        LOGGER.error("%s", error)
        return 2

    configure_logging(args.verbose)

    args.manifest = args.manifest.expanduser().resolve()
    args.output_root = args.output_root.expanduser().resolve()
    args.rmc_jar = args.rmc_jar.expanduser().resolve()
    args.spec = args.spec.expanduser().resolve()
    args.evaluator = args.evaluator.expanduser().resolve()

    if not validate_paths(args):
        return 1

    try:
        manifest = load_json(args.manifest)
    except (OSError, json.JSONDecodeError) as error:
        LOGGER.error(
            "Could not load candidate manifest: %s",
            error,
        )
        return 1

    if not isinstance(manifest, list):
        LOGGER.error("Candidate manifest must be a JSON array.")
        return 1

    selected_candidates = filter_candidates(
        manifest=manifest,
        candidate_ids=args.candidate_id,
        prompt_strategies=args.prompt_strategy,
        limit=args.limit,
    )

    LOGGER.info(
        "Manifest experiments: %d",
        len(manifest),
    )
    LOGGER.info(
        "Selected semantic candidates: %d",
        len(selected_candidates),
    )

    if args.dry_run:
        print()
        print("=" * 80)
        print("SEMANTIC BATCH DRY RUN")
        print("=" * 80)

        for index, candidate in enumerate(
            selected_candidates,
            start=1,
        ):
            print(
                f"{index:03d} | "
                f"{candidate.get('prompt_strategy')} | "
                f"{candidate.get('setting')} | "
                f"{candidate.get('candidate_id')}"
            )

        print("=" * 80)
        return 0

    reports_directory = args.output_root / "reports"
    executions_root = args.output_root / "executions"

    reports_directory.mkdir(parents=True, exist_ok=True)
    executions_root.mkdir(parents=True, exist_ok=True)

    results_json_path = reports_directory / "semantic_results.json"

    previous_raw = load_previous_results(results_json_path)

    results_by_id: dict[str, BatchResult] = {}

    for candidate_id, previous in previous_raw.items():
        try:
            results_by_id[candidate_id] = BatchResult(**previous)
        except TypeError:
            LOGGER.warning(
                "Ignoring incompatible previous result: %s",
                candidate_id,
            )

    total_selected = len(selected_candidates)

    for index, candidate in enumerate(
        selected_candidates,
        start=1,
    ):
        candidate_id = str(candidate.get("candidate_id"))
        previous = previous_raw.get(candidate_id)

        if should_skip_previous(
            previous=previous,
            resume=args.resume,
            rerun_failed=args.rerun_failed,
        ):
            LOGGER.info(
                "[%d/%d] SKIP %s (%s)",
                index,
                total_selected,
                candidate_id,
                previous.get("overall_status"),
            )
            continue

        LOGGER.info(
            "[%d/%d] RUN  %s | %s | %s",
            index,
            total_selected,
            candidate.get("prompt_strategy"),
            candidate.get("setting"),
            candidate_id,
        )

        try:
            result = run_candidate(
                candidate=candidate,
                args=args,
                executions_root=executions_root,
            )

        except Exception as error:
            LOGGER.exception(
                "Unexpected failure for candidate %s",
                candidate_id,
            )

            started_at = utc_now()
            result = make_base_result(
                candidate=candidate,
                started_at=started_at,
            )

            result.overall_status = STATUS_EVALUATOR_ERROR
            result.error_stage = "runner_internal_error"
            result.error_message = str(error)
            result.finished_at = utc_now()

        results_by_id[candidate_id] = result

        candidate_result_path = (
            Path(result.workspace_path) / "final_result.json"
            if result.workspace_path
            else reports_directory
            / "individual_results"
            / f"{safe_name(candidate_id)}.json"
        )

        write_json(
            candidate_result_path,
            asdict(result),
        )

        save_reports(
            reports_directory=reports_directory,
            results_by_id=results_by_id,
            manifest=manifest,
        )

        LOGGER.info(
            "[%d/%d] DONE %s | %s | %.2fs",
            index,
            total_selected,
            candidate_id,
            result.overall_status,
            result.elapsed_seconds,
        )

    save_reports(
        reports_directory=reports_directory,
        results_by_id=results_by_id,
        manifest=manifest,
    )

    final_summary = load_json(reports_directory / "semantic_summary.json")

    print()
    print("=" * 80)
    print("BATCH SEMANTIC VALIDATION COMPLETED")
    print("=" * 80)
    print(f"Total experiments       : " f"{final_summary['total_experiments']}")
    print(f"Syntax passed           : " f"{final_summary['syntax_passed']}")
    print(f"Syntax failed           : " f"{final_summary['syntax_failed']}")
    print(f"Semantic candidates     : " f"{final_summary['semantic_candidates']}")
    print(f"Semantic executed       : " f"{final_summary['semantic_executed']}")
    print(f"Semantic passed         : " f"{final_summary['semantic_passed']}")
    print(f"Semantic failed         : " f"{final_summary['semantic_failed']}")
    print(f"Infrastructure errors   : " f"{final_summary['infrastructure_errors']}")
    print("-" * 80)
    print(
        f"Results JSON            : " f"{reports_directory / 'semantic_results.json'}"
    )
    print(f"Results CSV             : " f"{reports_directory / 'semantic_results.csv'}")
    print(
        f"Summary                 : " f"{reports_directory / 'semantic_summary.json'}"
    )
    print("=" * 80)

    return 0


if __name__ == "__main__":
    sys.exit(main())
