"""Run the stable semantic stages using C++ already generated by syntax RMC."""

from __future__ import annotations

import json
import sys
import time
from pathlib import Path

from semantic_validation.core.evaluator_registry import get_benchmark_config
from src.artifacts.result_models import SemanticResult, SyntaxResult
from src.artifacts.workspace import WorkspaceManager
from src.syntax.rmc_compiler import CommandResult, CommandRunner


class SemanticValidator:
    def __init__(
        self,
        *,
        project_root: str | Path,
        gpp_bin: str = "g++",
        compile_timeout: int = 120,
        model_checker_timeout: int = 300,
        evaluator_timeout: int = 120,
        runner: CommandRunner | None = None,
    ) -> None:
        self.project_root = Path(project_root).resolve()
        self.gpp_bin = gpp_bin
        self.compile_timeout = compile_timeout
        self.model_checker_timeout = model_checker_timeout
        self.evaluator_timeout = evaluator_timeout
        self.runner = runner or CommandRunner()
        self.parser_script = (
            self.project_root
            / "semantic_validation"
            / "rebeca"
            / "rmc_result_parser.py"
        )

    def _run_stage(
        self,
        *,
        stage: str,
        command: list[str],
        cwd: Path,
        timeout: int,
        log_dir: Path,
        command_records: list[dict[str, object]],
    ) -> CommandResult:
        result = self.runner.run(command, cwd=cwd, timeout_seconds=timeout)
        stdout_path = log_dir / f"{stage}_stdout.log"
        stderr_path = log_dir / f"{stage}_stderr.log"
        WorkspaceManager.write_text(stdout_path, result.stdout)
        WorkspaceManager.write_text(stderr_path, result.stderr)
        record = result.to_dict()
        record.update(
            {
                "stage": stage,
                "stdout_path": str(stdout_path),
                "stderr_path": str(stderr_path),
            }
        )
        command_records.append(record)
        return result

    @staticmethod
    def _failure(
        *,
        started: float,
        stage: str,
        message: str,
        spec_path: Path,
        commands: list[dict[str, object]],
    ) -> SemanticResult:
        return SemanticResult(
            executed=True,
            passed=None,
            status="INFRA_ERROR",
            duration_seconds=time.monotonic() - started,
            error_stage=stage,
            error_message=message,
            spec_path=str(spec_path),
            commands=commands,
        )

    @staticmethod
    def _command_error(result: CommandResult) -> str:
        return (
            result.error
            or result.stderr.strip()
            or result.stdout.strip()
            or f"Command exited with code {result.return_code}."
        )

    @staticmethod
    def _extract_summary(payload: dict[str, object]) -> dict[str, object]:
        summary = payload.get("summary")
        return summary if isinstance(summary, dict) else payload

    def validate(
        self,
        *,
        syntax_result: SyntaxResult,
        attempt_root: Path,
        benchmark: str,
    ) -> SemanticResult:
        started = time.monotonic()
        config = get_benchmark_config(benchmark)
        commands: list[dict[str, object]] = []

        if not syntax_result.passed or not syntax_result.generated_cpp_path:
            return SemanticResult(
                executed=False,
                passed=None,
                status="NOT_RUN",
                error_message="Semantic validation requires a syntax-valid RMC candidate.",
                spec_path=str(config.spec_path),
            )

        generated_cpp = Path(syntax_result.generated_cpp_path)
        semantic_dir = attempt_root / "semantic"
        semantic_dir.mkdir(parents=False, exist_ok=False)
        cpp_files = sorted(generated_cpp.glob("*.cpp"))
        if not cpp_files:
            return self._failure(
                started=started,
                stage="cpp_discovery",
                message=f"No generated C++ files found in {generated_cpp}",
                spec_path=config.spec_path,
                commands=commands,
            )

        model_checker = generated_cpp / "model_checker"
        compile_result = self._run_stage(
            stage="cpp_compile",
            command=[
                self.gpp_bin,
                "-std=c++11",
                *[path.name for path in cpp_files],
                "-o",
                model_checker.name,
            ],
            cwd=generated_cpp,
            timeout=self.compile_timeout,
            log_dir=semantic_dir,
            command_records=commands,
        )
        if compile_result.return_code != 0 or not model_checker.is_file():
            return self._failure(
                started=started,
                stage="cpp_compilation",
                message=self._command_error(compile_result),
                spec_path=config.spec_path,
                commands=commands,
            )

        # Preserve the proven model-checker contract: result.xml is emitted
        # beside the generated checker and retained as an attempt artifact.
        trace_xml = generated_cpp / "result.xml"
        checker_result = self._run_stage(
            stage="model_checker",
            command=[str(model_checker), "-o", trace_xml.name],
            cwd=generated_cpp,
            timeout=self.model_checker_timeout,
            log_dir=semantic_dir,
            command_records=commands,
        )
        if checker_result.return_code != 0 or not trace_xml.is_file():
            return self._failure(
                started=started,
                stage="model_checker",
                message=self._command_error(checker_result),
                spec_path=config.spec_path,
                commands=commands,
            )

        parsed_json = semantic_dir / "parsed_result.json"
        parser_result = self._run_stage(
            stage="trace_parser",
            command=[
                sys.executable,
                str(self.parser_script),
                str(trace_xml),
                "-o",
                str(parsed_json),
            ],
            cwd=self.project_root,
            timeout=self.evaluator_timeout,
            log_dir=semantic_dir,
            command_records=commands,
        )
        if parser_result.return_code != 0 or not parsed_json.is_file():
            return self._failure(
                started=started,
                stage="trace_parser",
                message=self._command_error(parser_result),
                spec_path=config.spec_path,
                commands=commands,
            )

        semantic_json = semantic_dir / "semantic_result.json"
        evaluator_result = self._run_stage(
            stage="evaluator",
            command=[
                sys.executable,
                str(config.evaluator_path),
                str(parsed_json),
                "-o",
                str(semantic_json),
            ],
            cwd=self.project_root,
            timeout=self.evaluator_timeout,
            log_dir=semantic_dir,
            command_records=commands,
        )
        if evaluator_result.return_code != 0 or not semantic_json.is_file():
            return self._failure(
                started=started,
                stage="evaluator",
                message=self._command_error(evaluator_result),
                spec_path=config.spec_path,
                commands=commands,
            )

        payload = json.loads(semantic_json.read_text(encoding="utf-8"))
        summary = self._extract_summary(payload)
        semantic_pass = bool(summary.get("semantic_pass", False))
        passed_tests = summary.get("passed_tests", summary.get("passed"))
        failed_tests = summary.get("failed_tests", summary.get("failed"))
        not_observed = summary.get(
            "not_observed_tests", summary.get("not_observed", 0)
        )
        total_tests = summary.get("total_tests", summary.get("total"))
        failed_ids = summary.get("failed_test_ids", [])
        not_observed_ids = summary.get("not_observed_test_ids", [])

        if semantic_pass:
            status = "SEMANTIC_PASS"
        elif not_observed and not failed_tests:
            status = "SEMANTIC_NOT_OBSERVED"
        else:
            status = "SEMANTIC_FAIL"

        return SemanticResult(
            executed=True,
            passed=semantic_pass,
            status=status,
            duration_seconds=time.monotonic() - started,
            passed_tests=int(passed_tests) if passed_tests is not None else None,
            failed_tests=int(failed_tests) if failed_tests is not None else None,
            not_observed_tests=(
                int(not_observed) if not_observed is not None else None
            ),
            total_tests=int(total_tests) if total_tests is not None else None,
            failed_test_ids=list(failed_ids),
            not_observed_test_ids=list(not_observed_ids),
            trace_xml_path=str(trace_xml),
            parsed_result_path=str(parsed_json),
            result_path=str(semantic_json),
            spec_path=str(config.spec_path),
            commands=commands,
        )
